#!/bin/sh
### BEGIN INIT INFO
# Provides:          sysd
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops sysd
# Description:       System information api server.
### END INIT INFO

DAEMON=/home/yan/go/src/github.com/hacking-thursday/sysd/sysd/sysd

case "$1" in
start)
        start-stop-daemon --start --background --exec $DAEMON
;;
stop)
        start-stop-daemon --stop --name sysd
esac
