#!/bin/sh
### BEGIN INIT INFO
# Provides:          sysd
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops sysd
# Description:       System information api server.
### END INIT INFO

NAME=sysd
DAEMON=/usr/bin/sysd

do_start () {
        start-stop-daemon --start --background --quiet --exec $DAEMON
}

do_stop () {
        start-stop-daemon --stop --quiet --oknodo --retry=TERM/30/KILL/5 --exec $DAEMON
}

case "$1" in
  start)
        do_start
        ;;
  restart)
        do_stop
        do_start
        ;;
  stop)
        do_stop
        ;;
  *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
        exit 3
        ;;
esac
